// Code generated by MockGen. DO NOT EDIT.
// Source: bigtable.go

// Package domain is a generated GoMock package.
package domain

import (
	bigtable "cloud.google.com/go/bigtable"
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockBigtableRepository is a mock of BigtableRepository interface
type MockBigtableRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBigtableRepositoryMockRecorder
}

// MockBigtableRepositoryMockRecorder is the mock recorder for MockBigtableRepository
type MockBigtableRepositoryMockRecorder struct {
	mock *MockBigtableRepository
}

// NewMockBigtableRepository creates a new mock instance
func NewMockBigtableRepository(ctrl *gomock.Controller) *MockBigtableRepository {
	mock := &MockBigtableRepository{ctrl: ctrl}
	mock.recorder = &MockBigtableRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBigtableRepository) EXPECT() *MockBigtableRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockBigtableRepository) Get(ctx context.Context, table, key string, opts ...bigtable.ReadOption) (*Bigtable, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, table, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*Bigtable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockBigtableRepositoryMockRecorder) Get(ctx, table, key interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, table, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBigtableRepository)(nil).Get), varargs...)
}

// GetRows mocks base method
func (m *MockBigtableRepository) GetRows(ctx context.Context, table string, rr bigtable.RowRange, opts ...bigtable.ReadOption) (*Bigtable, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, table, rr}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRows", varargs...)
	ret0, _ := ret[0].(*Bigtable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRows indicates an expected call of GetRows
func (mr *MockBigtableRepositoryMockRecorder) GetRows(ctx, table, rr interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, table, rr}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRows", reflect.TypeOf((*MockBigtableRepository)(nil).GetRows), varargs...)
}

// Count mocks base method
func (m *MockBigtableRepository) Count(ctx context.Context, table string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, table)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count
func (mr *MockBigtableRepositoryMockRecorder) Count(ctx, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockBigtableRepository)(nil).Count), ctx, table)
}

// Tables mocks base method
func (m *MockBigtableRepository) Tables(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tables", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tables indicates an expected call of Tables
func (mr *MockBigtableRepositoryMockRecorder) Tables(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tables", reflect.TypeOf((*MockBigtableRepository)(nil).Tables), ctx)
}
